class_name TileIndex
extends RefCounted

## GENERATED by tools/gen_assets.py - do not edit by hand.

const TILE_SIZE := 16
const COLUMNS := 16
const SHEET_PATH := "res://assets/tiles.png"
const WATER_SHEET := "res://assets/water.png"

const INDEX := {
	"grass": 0,
	"grass~1": 1,
	"grass~2": 2,
	"grass_flowers": 3,
	"grass_flowers~1": 4,
	"grass_dark": 5,
	"grass_dark~1": 6,
	"dirt": 7,
	"dirt~1": 8,
	"path": 9,
	"path~1": 10,
	"stone_floor": 11,
	"stone_floor~1": 12,
	"stone_floor~2": 13,
	"brick_floor": 14,
	"brick_floor~1": 15,
	"wood_floor": 16,
	"rug": 17,
	"marble_floor": 18,
	"marble_floor~1": 19,
	"marble_floor~2": 20,
	"sand": 21,
	"sand~1": 22,
	"void": 23,
	"water": 24,
	"water_deep": 25,
	"lava": 26,
	"bridge": 27,
	"stone_wall": 28,
	"stone_wall_top": 29,
	"wood_wall": 30,
	"roof": 31,
	"marble_wall": 32,
	"moss_stone": 33,
	"moss_stone~1": 34,
	"gold_trim": 35,
	"window_wall": 36,
	"house_door": 37,
	"fence": 38,
	"pillar": 39,
	"grate": 40,
	"cobweb": 41,
	"tree": 42,
	"bush": 43,
	"rock": 44,
	"rubble": 45,
	"crate": 46,
	"barrel": 47,
	"chest_closed": 48,
	"chest_open": 49,
	"stairs_down": 50,
	"stairs_up": 51,
	"brazier_off": 52,
	"brazier_on": 53,
	"lantern_off": 54,
	"lantern_on": 55,
	"crystal": 56,
	"core_glow": 57,
	"flower_red": 58,
	"grass_tuft": 59,
	"grass_tuft~1": 60,
	"mushroom": 61,
	"sign": 62,
	"hole": 63,
	"arch": 64,
}


## Tile name -> interchangeable atlas frames. LevelBuilder picks one
## per cell from a stable hash, so large fields of one tile stop
## reading as a repeating grid.
const VARIANTS := {
	"brick_floor": [14, 15],
	"dirt": [7, 8],
	"grass": [0, 1, 2],
	"grass_dark": [5, 6],
	"grass_flowers": [3, 4],
	"grass_tuft": [59, 60],
	"marble_floor": [18, 19, 20],
	"moss_stone": [33, 34],
	"path": [9, 10],
	"sand": [21, 22],
	"stone_floor": [11, 12, 13],
}


static func id(name: String) -> int:
	return int(INDEX.get(name, 0))


static func has(name: String) -> bool:
	return INDEX.has(name)


static func variant_for(name: String, cell_x: int, cell_y: int) -> int:
	var frames: Array = VARIANTS.get(name, [])
	if frames.is_empty():
		return id(name)
	var h := (cell_x * 73856093) ^ (cell_y * 19349663)
	return int(frames[absi(h) % frames.size()])
